#server.port=80
#server.port.a=true
#server.port.b=true

server:
   port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/c76-s3-xm
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
 
  servlet:
     multipart:
        maxFileSize: 1000000000
        
  

mybatis:
  #实体类的路径
  type-aliases-package: com.yc.xm.bean
  configuration:
     map-underscore-to-camel-case: true
  
# 日志配置
logging:
  level:
    com:
      yc:
        xm:
          dao: debug
          web: warn

         

